services:
  mcp-outline-server:
    build: .
    container_name: mcp-outline-remote-v3
    restart: unless-stopped
    ports:
      - "3131:3131"
    environment:
      # Session Configuration - REQUIRED
      - SESSION_SECRET=${SESSION_SECRET}
      
      # Outline Configuration - REQUIRED  
      - OUTLINE_API_URL=${OUTLINE_API_URL}
      - OUTLINE_API_TOKEN=${OUTLINE_API_TOKEN}
      
      # MCP OAuth Configuration (Azure AD)
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_REDIRECT_URI=${AZURE_REDIRECT_URI}
      
      # OAuth Settings
      - ALLOWED_REDIRECT_URIS=${ALLOWED_REDIRECT_URIS:-https://claude.ai/api/mcp/auth_callback}
      - OAUTH_ISSUER=${OAUTH_ISSUER}
      
      # Server Configuration
      - PORT=3131
      - PUBLIC_URL=${PUBLIC_URL}
      - NODE_ENV=${NODE_ENV:-production}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - mcp-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3131/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: mcp-outline-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  mcp-network:
    driver: bridge